import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <nav
          style={{
            padding: "1rem 2rem",
            background: "#1f2937",
            display: "flex",
            gap: "2rem",
            justifyContent: "center",
            color: "white",
          }}
        >
          <Link href="/" style={{ color: "white" }}>
            Home
          </Link>
          <Link href="/quienes-somos" style={{ color: "white" }}>
            Quiénes somos
          </Link>
          <Link href="/proyectos" style={{ color: "white" }}>
            Proyectos
          </Link>
          <Link href="/galeria" style={{ color: "white" }}>
            Galería
          </Link>
          <Link href="/contacto" style={{ color: "white" }}>
            Contacto
          </Link>
        </nav>
        <main style={{ padding: "2rem" }}>{children}</main>
      </body>
    </html>
  );
}
